# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build SwiftGitX
      run: swift build -v
    - name: Update git configurations
      run: >
          git config --global init.defaultBranch main &&
          git config --global user.name "İbrahim Çetin" &&
          git config --global user.email "mail@ibrahimcetin.dev"
    - name: Run tests
      run: swift test -v
